image:
  repository: 345678901234.dkr.ecr.us-east-1.amazonaws.com/fastapi-template
  tag: latest

resources:
  requests:
    cpu: 512m
    memory: 200Mi
  limits:
    cpu: 512m
    memory: 200Mi

hpa:
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 50

env:
  stage: prod
