image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/fastapi-template
  tag: latest

resources:
  requests:
    cpu: 512m
    memory: 200Mi
  limits:
    cpu: 512m
    memory: 200Mi

hpa:
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 50

env:
  stage: dev
