name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.py'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7.35
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: default
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_ROOT_PASSWORD: mysql
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get full Python version
        id: full-python-version
        shell: bash
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - name: Bootstrap poetry
        shell: bash
        run: pip install poetry

      - name: Update PATH
        shell: bash
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-ubuntu-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        shell: bash
        run: timeout 10s poetry run pip --version || rm -rf .venv

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Lint
        shell: bash
        run: make lint

      - name: Alembic test
        env:
          DB_HOST: 127.0.0.1
          DB_NAME: default
          DB_USER: root
          DB_PASSWORD: mysql
        shell: bash
        run: make prestart

      - name: Test
        env:
          TEST_DB_HOST: 127.0.0.1
          TEST_DB_NAME: default
          TEST_DB_USER: root
          TEST_DB_PASSWORD: mysql
        shell: bash
        run: make test
